public class Exception1 {
    public static void main(String[] args) {
        int num1 = 5;
        int num2 = num1 / 0;
        System.out.println(num2);
        System.out.println("プログラムの最後です");
    }
}
